### ISSUE TITLE
com.google.inject.ProvisionException on start

### ISSUE THREAD

**Issue by PC1up** [smuddgge/Leaf#104]
`Leaf Version:` 5.2.0

**Description of the Bug**
Upon starting Velocity a ProvosionException is thrown.

**Console Errors**
Exception:
```
[13:15:35] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Can't create plugin leaf
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: RuntimeException: ClassNotFoundException: Driver
  at Leaf.<init>(Leaf.java:75)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating Leaf

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
Driver:                 "com.mysql.jdbc.Driver"
Leaf:                   "com.github.smuddgge.leaf.Leaf"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:131) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:362) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:239) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at com.github.smuddgge.leaf.Leaf.setupDatabase(Leaf.java:359) ~[?:?]
	at com.github.smuddgge.leaf.Leaf.<init>(Leaf.java:85) ~[?:?]
	at com.github.smuddgge.leaf.Leaf$$FastClassByGuice$$d9a2c.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at com.github.smuddgge.leaf.Leaf$$FastClassByGuice$$d9a2c.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.github.smuddgge.leaf.Leaf.setupDatabase(Leaf.java:357) ~[?:?]
	at com.github.smuddgge.leaf.Leaf.<init>(Leaf.java:85) ~[?:?]
	at com.github.smuddgge.leaf.Leaf$$FastClassByGuice$$d9a2c.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at com.github.smuddgge.leaf.Leaf$$FastClassByGuice$$d9a2c.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity.jar:3.3.0-SNAPSHOT (git-07f1f9e7-b396)]
	... 6 more
```

Entire log: https://paste.md-5.net/ayayixegid.txt
No matter what I choose as type in `database.yml`, this error always occurs.

**OS:** Archlinux 6.9.3-arch1-1
**Velocity Version:** 3.3.0-SNAPSHOT

**Comment by smuddgge** [comment]
Please try version `5.2.1`. If it still creates errors let me know :3
