### ISSUE TITLE
[BUG] Protocolize Error

### ISSUE THREAD

**Issue by JosTheDude** [smuddgge/Leaf#33]
`Leaf Version:` 3.0.0

**Description of the Bug**
No request to download protocolize when it's missing for the GUIs

**Console Errors**
```
Caused by: java.lang.RuntimeException: Unable to invoke command adminmenu for [connected player] SkipTurn (/69.118.50.65:65024)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:226) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:251) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: dev/simplix/protocolize/api/inventory/Inventory
        at com.github.smuddgge.leaf.inventorys.InventoryInterface.open(InventoryInterface.java:39) ~[?:?]
        at com.github.smuddgge.leaf.commands.types.Inventory.onPlayerRun(Inventory.java:51) ~[?:?]
        at com.github.smuddgge.leaf.commands.Command.onPlayerRun(Command.java:123) ~[?:?]
        at com.github.smuddgge.leaf.commands.Command.execute(Command.java:221) ~[?:?]
        at com.github.smuddgge.leaf.commands.Command.execute(Command.java:26) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:213) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:251) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: dev.simplix.protocolize.api.inventory.Inventory
        at com.github.smuddgge.leaf.inventorys.InventoryInterface.open(InventoryInterface.java:39) ~[?:?]
        at com.github.smuddgge.leaf.commands.types.Inventory.onPlayerRun(Inventory.java:51) ~[?:?]
        at com.github.smuddgge.leaf.commands.Command.onPlayerRun(Command.java:123) ~[?:?]
        at com.github.smuddgge.leaf.commands.Command.execute(Command.java:221) ~[?:?]
        at com.github.smuddgge.leaf.commands.Command.execute(Command.java:26) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:213) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:251) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```

**Comment by smuddgge** [comment]
Is this bug replecated by not using the dependency protocolize? :3
If so are you suggesting having the plugin tell the user that they need it for inventory?
I don't think I can download it for them

**Comment by JosTheDude** [comment]
Yes, possibly disabling inventories till they download it could also assist as well :)

**Comment by smuddgge** [comment]
Should be fixed now, thank you for reporting :3
