### ISSUE TITLE
Disconnection event spam when servers are not set

### ISSUE THREAD

**Issue by JosTheDude** [smuddgge/Leaf#5]
```
[03:36:47 ERROR]: Couldn't pass DisconnectEvent to leaf
java.lang.NullPointerException: Cannot invoke "com.velocitypowered.api.proxy.server.RegisteredServer.getServerInfo()" because "server" is null
        at com.github.smuddgge.leaf.datatype.User.addHistory(User.java:191) ~[?:?]
        at com.github.smuddgge.leaf.events.EventManager.onPlayerLeave(EventManager.java:56) ~[?:?]
        at com.github.smuddgge.leaf.Leaf.onPlayerLeave(Leaf.java:108) ~[?:?]
        at com.github.smuddgge.leaf.Lmbda$14.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-8deb0ff7-b198)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

This error is sent whenever a server isn't specified when someone disconnects (unconfigured server)

**Comment by smuddgge** [comment]
Hey, what version are you using currently? I believe I fixed this issue in the latest version :3

**Comment by smuddgge** [comment]
If it is still occurring on the most up-to-date version feel free to create a new issue :3
